// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv6zzG0TU08WdIhdXea8KzZjasmVB70HE',
    appId: '1:977656217880:android:00f299ab3f38ad10781e6d',
    messagingSenderId: '977656217880',
    projectId: 'fir-71726',
    storageBucket: 'fir-71726.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAXPDFAudzTuJY1HxYWADlsxUv6jHcvn8',
    appId: '1:977656217880:ios:76c84a3e7f97da66781e6d',
    messagingSenderId: '977656217880',
    projectId: 'fir-71726',
    storageBucket: 'fir-71726.appspot.com',
    iosClientId: '977656217880-o3n8pp7b510k2n4be7r0ousfpbfs70t6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAXPDFAudzTuJY1HxYWADlsxUv6jHcvn8',
    appId: '1:977656217880:ios:8a65004eb47a84f6781e6d',
    messagingSenderId: '977656217880',
    projectId: 'fir-71726',
    storageBucket: 'fir-71726.appspot.com',
    iosClientId: '977656217880-o6k14nu9uo2jictitb376iei7a9pelti.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
